---
title: "ClassifierComparison"
author: "Bart"
date: "4/13/2021"
output: html_document
---
For now this is using functions from other scripts. 05 and viz functions.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# This runs models and plots the outputs.
get_smooths <- function(pred_results,title_text,plot_color="black"){
  
  # Fit distance from the classification hyperplane, a continuous measure, as a function of age and covariates using GAM.
  cat("\nDevelopmental models for  distance\n")
  pred_results$Distance = as.numeric(pred_results$distance)

  # GAM
  cat("\nGAM\n")
  gam_model <- gam(Distance ~s(age,k=4)+ oSex+FD+ idemoBehAllEmoNrCount, data = pred_results,
                 subset = exclusions==0)
  smooth_est <- gratia::smooth_estimates(gam_model)
  
  return(smooth_est)
}
```

## Schaefer 200

```{r s200, eval = TRUE}
atlasname= "schaefer200x7_aal"
schaef200_results <- data_mgmt('/cbica/projects/alpraz_EI/output/PNC_predictions/schaefer200x7_aal_all_FD5.rds')
schaef200_smooth <- get_smooths(schaef200_results)
schaef200_smooth$parcellation = "schaef200"
display_results("schaefer200x7_aal",perm_results = T)
# plot_results(pred_results,"Schaefer200_All_Regions")

schaef200 <- readRDS(sprintf("/cbica/projects/alpraz_EI/output/drug_classification/%s_GSR_all_svm_1_permute_on_FD5results.rds",
                                   atlasname))
schaef200 <- schaef200[[1]]

```

## Schaefer 400

```{r s400, eval = TRUE}
atlasname= "schaefer400x7_aal"
schaef400_results <- data_mgmt('/cbica/projects/alpraz_EI/output/PNC_predictions/schaefer400x7_aal_all_FD5.rds')
schaef400_smooth <- get_smooths(schaef400_results)
schaef400_smooth$parcellation = "schaef400"
# display_results("schaefer400x7_aal",perm_results = T)
# plot_results(pred_results,"Schaefer400_All_Regions")

schaef400 <- readRDS(sprintf("/cbica/projects/alpraz_EI/output/drug_classification/%s_GSR_all_svm_1_permute_on_FD5results.rds",
                                   atlasname))
schaef400 <- schaef400[[1]]

```

### AAL

```{r aal,eval=TRUE}
atlasname= "aal116"
aal_results <- data_mgmt('/cbica/projects/alpraz_EI/output/PNC_predictions/aal116_all_FD5.rds')
aal_smooth <- get_smooths(aal_results)
aal_smooth$parcellation = "aal"
display_results("aal116",perm_results = T)
# plot_results(pred_results,"AAL: All Regions")

aal <- readRDS(sprintf("/cbica/projects/alpraz_EI/output/drug_classification/%s_GSR_all_svm_1_permute_on_FD5results.rds",
                                   atlasname))
aal <- aal[[1]]
```

### Glasser

```{r Glasser,eval=TRUE}
atlasname= "glasser360_aal"
glasser_results <- data_mgmt('/cbica/projects/alpraz_EI/output/PNC_predictions/glasser360_aal_all_FD5.rds')
glasser_smooth <- get_smooths(glasser_results)
glasser_smooth$parcellation = "glasser"
# display_results("glasser360_aal",perm_results = T)
# plot_results(pred_results,"Glasser: All Regions")
# 
glasser <- readRDS(sprintf("/cbica/projects/alpraz_EI/output/drug_classification/%s_GSR_all_svm_1_permute_on_FD5results.rds",
                                   atlasname))
glasser <- glasser[[1]]
```

### Gordon
```{r Gordon,eval=TRUE}
atlasname= "gordon333_aal"
gordon_results <- data_mgmt('/cbica/projects/alpraz_EI/output/PNC_predictions/gordon333_aal_all_FD5.rds')
gordon_smooth <- get_smooths(gordon_results)
gordon_smooth$parcellation = "gordon"
# display_results("gordon333_aal",perm_results = T)
# plot_results(pred_results,"Gordon: All Regions")

gordon <- readRDS(sprintf("/cbica/projects/alpraz_EI/output/drug_classification/%s_GSR_all_svm_1_permute_on_FD5results.rds",
                                   atlasname))
gordon <- gordon[[1]]
```

### Compare
```{r comparison}
gordon_df <- data.frame(perm_acc = gordon$perm_accs,parcellation = "gordon")
aal_df <- data.frame(perm_acc = aal$perm_accs,parcellation = "aal")
glasser_df <- data.frame(perm_acc = glasser$perm_accs,parcellation = "glasser")
schaef200_df <- data.frame(perm_acc = schaef200$perm_accs,parcellation = "schaef200")
schaef400_df <- data.frame(perm_acc = schaef400$perm_accs,parcellation = "schaef400")

combined <- rbind(gordon_df,aal_df,glasser_df,schaef200_df,schaef400_df)
true_accuracy = data.frame(accuracy = c(gordon$accuracy,glasser$accuracy,aal$accuracy,schaef200$accuracy,schaef400$accuracy),
                           parcellation = c("gordon","glasser","aal","schaef200","schaef400"))

ggplot(data = combined, aes(x=perm_acc,group=parcellation,fill=parcellation,color=parcellation))+
  geom_histogram(alpha=.92,position = "dodge")+
  scale_color_brewer(type = "qual",palette = "Dark2",direction = -1)+
  scale_fill_brewer(type = "qual",palette = "Dark2",direction = -1)+
  geom_vline(data=true_accuracy,aes(xintercept = accuracy,color=parcellation),line_size=line_size)+
  xlab("Accuracy")+ylab("# of draws")


gordon_df <- data.frame(perm_auc = gordon$perm_aucs,parcellation = "Gordon Cortical Atlas")
aal_df <- data.frame(perm_auc = aal$perm_aucs,parcellation = "AAL")
glasser_df <- data.frame(perm_auc = glasser$perm_aucs,parcellation = "Multi-modal Parcellation Atlas")
schaef200_df <- data.frame(perm_auc = schaef200$perm_aucs,parcellation = "Schaefer 200")
schaef400_df <- data.frame(perm_auc = schaef400$perm_aucs,parcellation = "Schaefer 400")

combined <- rbind(gordon_df,aal_df,glasser_df,schaef200_df,schaef400_df)
true_AUC = data.frame(AUC = c(.665,.726,.7074,.7069,.716),
                           parcellation = c("Gordon Cortical Atlas","Multi-modal Parcellation Atlas","AAL","Schaefer 200","Schaefer 400"))

ggplot(data = combined, aes(x=perm_auc,group=parcellation,fill=parcellation,color=parcellation))+
  geom_histogram(alpha=.92,position = "dodge")+
  scale_color_brewer(type = "qual",palette = "Dark2",direction = -1)+
  scale_fill_brewer(type = "qual",palette = "Dark2",direction = -1)+
  geom_vline(data=true_AUC,aes(xintercept = AUC,color=parcellation))+
  xlab("AUC")+ylab("# of draws")+
  theme(legend.position = "top")

```


```{r age_comparison}
age_combined <- rbind(gordon_smooth,glasser_smooth,aal_smooth,schaef200_smooth,schaef400_smooth) %>%
  mutate(ymins=est-se,ymaxs=est+se)

ggplot(data = age_combined,aes(x=age,y=est,color=parcellation,ymin=ymins,ymax=ymaxs,fill=parcellation)) +
  geom_ribbon(alpha=.25,color=NA)+
  geom_line(size=1)+
  scale_color_brewer(type = "qual",palette = "Dark2",direction = -1)+
  scale_fill_brewer(type = "qual",palette = "Dark2",direction = -1)+
  xlab("Age (years)") + ylab("Distance (centered)")

```
